name: Java CI

on:
  push:
    branches:
      - main # Exécution lors de push sur la branche main
  pull_request:
    branches:
      - main # Exécution lors des PR vers main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Configurer Java 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Construire avec Maven
        run: mvn clean install

      - name: Exécuter les tests
        run: mvn test
